# Generated by Django 5.2.3 on 2025-07-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sa', 'Super Admin'), ('a', 'Admin'), ('t', 'Teacher'), ('s', 'Student')], default='s', max_length=2),
        ),
    ]
