# Generated by Django 5.2.3 on 2025-07-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('s', 'Super Admin'), ('a', 'Admin'), ('t', 'Teacher')], default='t', max_length=2),
        ),
    ]
