# Generated by Django 5.2.3 on 2025-07-17 06:44

import app.users.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[app.users.validation.validate_phone_number]),
        ),
    ]
