# Generated by Django 5.2.3 on 2025-07-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('s', 'Super Admin'), ('a', 'Admin'), ('t', 'Teacher'), ('p', 'Parent')], default='t', max_length=2),
        ),
    ]
