# Generated by Django 5.2.3 on 2025-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('p', 'present'), ('a', 'absent'), ('e', 'empty')], default='e', max_length=1),
        ),
    ]
