# Generated by Django 5.2.3 on 2025-07-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
