# Generated by Django 5.2.3 on 2025-07-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_type'),
        ('students', '0008_remove_student_is_paid_studentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='students', to='groups.group'),
        ),
    ]
