# Generated by Django 5.2.3 on 2025-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_type'),
        ('students', '0009_remove_student_group_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(through='students.StudentGroup', to='groups.group'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('student', 'group')},
        ),
    ]
