# Generated by Django 5.2.3 on 2025-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_student_group_student_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
