# Generated by Django 5.2.3 on 2025-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentgroup_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='is_active',
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
