# Generated by Django 5.2.3 on 2025-07-14 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_type'),
        ('payments', '0002_alter_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(default='16437f0a-fb50-4200-9134-247089c90b72', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='groups.group'),
            preserve_default=False,
        ),
    ]
