# Generated by Django 5.2.3 on 2025-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=10),
            preserve_default=False,
        ),
    ]
