# Generated by Django 5.2.3 on 2025-07-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('e', 'Even day'), ('o', 'Odd day'), ('a', 'All day')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
