# Generated by Django 5.2.3 on 2025-07-10 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0004_group_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('teachers_salaries', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('benefit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('month', models.PositiveSmallIntegerField(blank=True, default=7)),
                ('year', models.PositiveSmallIntegerField(blank=True, default=2025)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=50)),
                ('month', models.PositiveSmallIntegerField(blank=True, default=7)),
                ('year', models.PositiveSmallIntegerField(blank=True, default=2025)),
                ('attendance_count', models.IntegerField(blank=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('calculate_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'group', 'month', 'year')},
            },
        ),
    ]
